CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS hashpwd (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL REFERENCES users(username),
    password VARCHAR(255) NOT NULL
);
